name: Build Flutter APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:  # Permet de lancer manuellement depuis GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
      checks: write

    steps:
    - uses: actions/checkout@v4
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.4'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Clean previous build
      run: flutter clean
    
    - name: Build APK
      run: flutter build apk --release
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30
